### PR TITLE
Add docs on fixing systemd-resolved issue

### PR DESCRIPTION
**Pull request by xatier**

### CODE REVIEW

**Comment by slingamn** [comment]
The reason I hesitated to provide this recommendation is that it's not a complete fix: in particular, it does not prevent applications from doing DNS resolution directly via systemd-resolved's [D-Bus interface](https://www.freedesktop.org/wiki/Software/systemd/resolved/) (it only blocks conventional name resolution via `getaddrinfo(3)`). Therefore, the recommended mitigation is to completely disable systemd-resolved.

Thoughts?

**Comment by xatier** [comment]
That's true, I agree with that this only blocks applications using `getaddressinfo` (GNU C library based ones). Direct use of D-Bus would still be available/problematic here.

What about adding the above info in my readme change? I can certainly do that.

**Comment by slingamn** [comment]
Given the current recommendation of disabling systemd-resolved entirely, I don't see that recommending a bind mount over nsswitch.conf really adds any value.

A bind mount of nsswitch.conf also has the same problems associated with a bind mount of resolv.conf (i.e., it can disappear without notice).

**Comment by xatier** [comment]
Feel free to drop this PR if you believe this adds no value here.

**Comment by slingamn** [comment]
Thanks for the discussion --- please let me know if you have any other suggestions or proposed contributions :-)

**Pull request closed without merging**
